redis:
  image: redis
  ports:
    - '6379'
stream:
  build: ./planet-stream
  env_file: .env
  links:
    - redis
api:
  build: ./osm-stats-api
  links:
    - redis
  ports:
    - "80:3000"
  env_file: .env