redis:
  image: redis
  ports:
    - '6379'
stream:
  build: ./planet-stream
  env_file: .env
  links:
    - redis
    - forgettable
  #log_driver: awslogs
  #log_opt:
  #  awslogs-group: "/aws/ec2/${DEPLOY_NAME}"
api:
  build: ./osm-stats-api
  links:
    - redis
    - forgettable
  ports:
    - 80:3000
  env_file: .env
  #log_driver: awslogs
  #log_opt:
  #  awslogs-group: "/aws/ec2/${DEPLOY_NAME}"
forgettable:
  build: ./forgettable
  ports:
    - 8080:8080
  links:
    - redis
  #log_driver: awslogs
  #log_opt:
  #  awslogs-group: "/aws/ec2/${DEPLOY_NAME}"
